In [11]:
import numpy as np
import cv2
import os

# Load the images using cv2
def load_images(image_dir, format=".TIF", channel=0):
    images = []
    for filename in os.listdir(image_dir):
        if filename.endswith(format):
            image_path = os.path.join(image_dir, filename)
            if format == ".JPG":
                image = cv2.imread(image_path, cv2.COLOR_BGR2RGB)/255  # Use IMREAD_UNCHANGED to load the image as-is
                # Extract only the first channel (R channel in RGB)
                first_channel = image[:, :, channel]
                image = first_channel 
            else:
                image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)/255  # Use IMREAD_UNCHANGED to load the image as-is
            if image is not None:
                images.append(image)
    return np.array(images)

# Calculate mean and standard deviation
def calculate_mean_std(images):
    all_images = np.stack(images, axis=0)
    mean = np.mean(all_images)
    std = np.std(all_images)
    return mean, std

# Normalize the images
def normalize_image(image, mean, std):
    return (image - mean) / std

def calculate_mean_std_3_channels(images):
    # Convert the image to float32 for precision
    # Stack images along a new dimension
    images_stack = np.stack(images, axis=0)
    
    # Calculate mean and std along the first axis (the stack axis)
    means = np.mean(images_stack, axis=(0, 1, 2))
    stds = np.std(images_stack, axis=(0, 1, 2))
    
    return means, stds

# Main function to normalize all images
def main(image_dir, format="_Blue.TIF", channel=0):
    images = load_images(image_dir, format=format, channel=channel)
    if len(images) == 0:
        raise ValueError("No images found in the specified directory.")
    if format == ".JPG":
        mean, std = calculate_mean_std_3_channels(images)
    else:
        mean, std = calculate_mean_std(images)
    #normalized_images = [normalize_image(image, mean, std) for image in images]
    return mean, std #normalized_images, mean, std

# Directory containing the TIF files
#image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
#mean, std = main(image_dir, format="_Blue.TIF")
#print(f'Mean: {mean}, Std: {std}')

In [24]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format="_Blue.TIF")
print(f'Mean: {mean}, Std: {std}')

Mean: 0.19921126550868484, Std: 0.08737094934046073


In [25]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format="_Green.TIF")
print(f'Mean: {mean}, Std: {std}')

Mean: 0.2158713264973507, Std: 0.1077127887804845


In [26]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format="_RE.TIF")
print(f'Mean: {mean}, Std: {std}')

Mean: 0.30553897323991464, Std: 0.1411584645612633


In [27]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format="_Red.TIF")
print(f'Mean: {mean}, Std: {std}')

Mean: 0.1877148050892823, Std: 0.0980950697163566


In [28]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format="_NIR.TIF")
print(f'Mean: {mean}, Std: {std}')

Mean: 0.39464298275190973, Std: 0.1565859098828533


In [ ]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
mean, std = main(image_dir, format=".JPG", channel=0)
print(f'Mean: {mean}, Std: {std}')

In [3]:
images = load_images('D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/', format=".JPG")
mean, std = calculate_mean_std_3_channels(images)
mean

0.41141770003162487

In [ ]:
# Pineapples dataset stats for blue, green, red, nir, re and rgb images

BLUE_MEAN  = 0.199
BLUE_STD   = 0.087

GREEN_MEAN = 0.216
GREEN_STD  = 0.108

RED_MEAN   = 0.188
RED_STD    = 0.098

NIR_MEAN   = 0.395
NIR_STD    = 0.157

RE_MEAN    = 0.306 
RE_STD     = 0.141

RGB_MEAN   = [0.485, 0.456, 0.406] # Using imagenet stats
RGB_STD    = [0.229, 0.224, 0.225] # Using imagenet stats

In [7]:
def load_images_paths(image_dir, format=".TIF"):
    images = []
    for filename in os.listdir(image_dir):
        if filename.endswith(format):
            image_path = os.path.join(image_dir, filename)
            #image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)  # Use IMREAD_UNCHANGED to load the image as-is
            #if image is not None:
            images.append(image_path)
    return images

In [8]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
images_paths = load_images_paths(image_dir, format=".JPG")
img = cv2.imread(images_paths[0], cv2.COLOR_RGB2BGR) #.shape
img.shape

(1300, 1600, 3)

In [22]:
img.astype(np.float32) / 255.0


array([[0.15686275, 0.15294118, 0.16078432, ..., 0.12941177, 0.1254902 ,
        0.1254902 ],
       [0.15294118, 0.15294118, 0.16078432, ..., 0.12941177, 0.1254902 ,
        0.12156863],
       [0.15294118, 0.15294118, 0.15686275, ..., 0.12941177, 0.1254902 ,
        0.1254902 ],
       ...,
       [0.16862746, 0.15686275, 0.14901961, ..., 0.32156864, 0.32941177,
        0.29803923],
       [0.15686275, 0.15294118, 0.15294118, ..., 0.33333334, 0.3137255 ,
        0.31764707],
       [0.15294118, 0.14901961, 0.15294118, ..., 0.35686275, 0.32156864,
        0.3254902 ]], dtype=float32)

In [21]:
mean = 50.79887270471464 
std = 22.279592081817448

(img - mean)/std

array([[-0.48469795, -0.52958208, -0.43981383, ..., -0.79888683,
        -0.84377096, -0.84377096],
       [-0.52958208, -0.52958208, -0.43981383, ..., -0.79888683,
        -0.84377096, -0.88865508],
       [-0.52958208, -0.52958208, -0.48469795, ..., -0.79888683,
        -0.84377096, -0.84377096],
       ...,
       [-0.35004558, -0.48469795, -0.5744662 , ...,  1.4004353 ,
         1.49020355,  1.13113055],
       [-0.48469795, -0.52958208, -0.52958208, ...,  1.53508768,
         1.31066705,  1.35555118],
       [-0.52958208, -0.5744662 , -0.52958208, ...,  1.80439243,
         1.4004353 ,  1.44531943]])

In [10]:
image_dir = 'D:/RESEARCH/pineapple_sam/multispectral_gira_10_13_mar21_lote71_5m/train2017/'
images_paths = load_images_paths(image_dir, format="_Blue.TIF")
cv2.imread(images_paths[0], cv2.IMREAD_UNCHANGED) #.shape

array([[10240, 10176, 10688, ...,  8448,  8256,  8192],
       [ 9984, 10112, 10624, ...,  8448,  8320,  7936],
       [10112,  9984, 10432, ...,  8576,  8320,  8384],
       ...,
       [11136, 10368,  9920, ..., 21184, 21568, 19584],
       [10240, 10048, 10176, ..., 21888, 20672, 20928],
       [ 9984,  9856, 10176, ..., 23424, 21184, 21376]], dtype=uint16)